baseURL = 'https://taskfiend.online/'
locale = 'en-us'
title = 'Task Fiend'
theme = 'hextra'

sectionPagesMenu = 'main'

cover_dimming_class = ''

[params]
  favicon = 'images/favicon.ico'
  custom_css = ["css/kj.css"]
